services:

  db-postgres:
    image: postgres:17-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db_data:/var/lib/postgresql/data


  db-redis:
    image: redis:7-alpine
    ports:
      - '6379:6379'
    depends_on:
      - db-postgres
    volumes:
      - ./redis_data:/var/lib/redis/data

  app-back:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    env_file:
      - .env
    depends_on:
      - db-postgres
      - db-redis
    command: [
      "bash", "-c", "
        sleep 10 && \
        alembic upgrade head && \
        bash start_api.sh"
    ]


  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - app-back
    env_file:
      - .env
    command: ["celery", "-A", "app.core.celery", "worker", "-l", "INFO"]